# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/dhnmagic"
  weibo: "http://www.weibo.com/p/1005052768243557"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:1016872941@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: https://haitao.nos.netease.com/decc8ed8-64a5-412d-99fd-adad26a18f8f_48_48.ico

#你的头像url
avatar:  https://haitao.nos.netease.com/9b598985-c1e0-4885-a628-055145a0ee00_300_480.jpg
#是否开启分享
share_jia: false
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 一个人的气质里，藏着他读过的书，走过的路，爱过的人。
